### ISSUE TITLE
builds against macOS, windows in CI step

### ISSUE THREAD

**Issue by ilias-ant** [ilias-ant/pydatagovgr#4]
**Proposal**

The CI procedure should also test against `macos-latest`, `windows-latest`.

```yml
...

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]
...

```
